### ISSUE TITLE
RFE: rolling update and GA version?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [xu-cheng/latex-docker#7]
Hi, 

The small/full release are based on the GA 2021 texlive releases if I am reading correctly. Could they be tagged as such?
Would it make sense to provide monthly tagged version  with `tlmgr update --self && tlmgr update -all` ?

Thanks

Tru

**Comment by xu-cheng** [comment]
The images actually are built monthly by GitHub Actions. Each time, it will fetch the latest packages to that date. So, the monthly tagged rolling release is already there. You can find them at https://github.com/users/xu-cheng/packages/container/texlive-full/versions

The releases in the recent month were not tagged properly, which results them to be only tagged with hash. But I think it should be fixed by https://github.com/xu-cheng/latex-docker/commit/41da6037fb69495f3e6fd7856a54d5efeb21099a

**Comment by truatpasteurdotfr** [comment]
neat, I missed that monthly tag info!
